server:
   port: 9002
eureka:
  instance:
    virtualHostName: fancyserver
    appGroupName: fancyGroup
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    easeRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true

