server:
   port: 9003
eureka:
  instance:
     virtualHostName: fancyclient
     appGroupName: fancyGroup
     statusPageUrlPath: ${management.context-path}/info
     healthCheckUrlPath: ${management.context-path}/health
     easeRenewalIntervalInSeconds: 10
  client:
     region: default
     registryFetchIntervalSeconds: 10
     availabilityZones:
         default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}